# Generated by Django 4.2 on 2023-04-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morrison', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapa',
            old_name='description',
            new_name='descripcion',
        ),
    ]
